/**
 * Claim Proof — The Turo Host's Damage-Claim Defense System.
 *
 * A three-tier, anonymous-checkout digital product (Be Nice Autos product,
 * sold on BNHG's payment rails) at benicehospitality.com/claimproof. Pattern
 * cloned from The Host's Edge (src/lib/hosts-edge.ts):
 *   - Stripe:  src/lib/stripe.ts (getStripe / getBaseUrl)
 *   - Webhook: src/app/api/webhooks/stripe/route.ts (metadata-tagged branch)
 *   - Email:   Resend (same client the rest of the app uses)
 *
 * Unlike Host's Edge this product is AUTHORED, not faceless — the pitch is
 * operator credibility ("built and used daily by a real fleet"). Three tiers
 * map to three Stripe Prices and three download URLs; tier travels in session
 * metadata so one webhook branch fulfills all of them.
 */

import { sql } from "@/lib/db";

/**
 * Stripe Checkout metadata tag marking a session as a Claim Proof purchase.
 * The shared webhook keys off this. Keep in sync with the checkout route and
 * the webhook branch — changing it silently breaks delivery.
 */
export const CLAIM_PROOF_PRODUCT_TAG = "claim-proof-turo-defense";

export type ClaimProofTier = "core" | "pro" | "fleet";

export const CLAIM_PROOF = {
  productTag: CLAIM_PROOF_PRODUCT_TAG,
  name: "Claim Proof — The Turo Host's Damage-Claim Defense System",
  /** Public route the product lives at. */
  path: "/claimproof",
} as const;

/** Display + pricing constants per tier. Price IDs come from env. */
export const CLAIM_PROOF_TIERS: Record<
  ClaimProofTier,
  { label: string; priceUsd: number; envPrice: string }
> = {
  core: {
    label: "Core Kit",
    priceUsd: 47,
    envPrice: "CLAIM_PROOF_STRIPE_PRICE_ID_CORE",
  },
  pro: {
    label: "Pro Kit",
    priceUsd: 97,
    envPrice: "CLAIM_PROOF_STRIPE_PRICE_ID_PRO",
  },
  fleet: {
    label: "Fleet Kit",
    priceUsd: 197,
    envPrice: "CLAIM_PROOF_STRIPE_PRICE_ID_FLEET",
  },
};

export function isClaimProofTier(t: unknown): t is ClaimProofTier {
  return t === "core" || t === "pro" || t === "fleet";
}

/** Stripe Price for a tier. Null when unset so routes can fail cleanly. */
export function getClaimProofPriceId(tier: ClaimProofTier): string | null {
  return process.env[CLAIM_PROOF_TIERS[tier].envPrice] || null;
}

/**
 * The download LINK a buyer receives — a stable, token-gated URL to our own
 * /api/claimproof/download endpoint (NOT the raw Blob URL). The endpoint
 * verifies the token and mints a fresh, short-lived signed URL from the
 * private Blob store per click. This is what goes in delivery emails: it never
 * expires, but "anyone with the link" still can't open the file without a
 * valid token, and the underlying Blob URL is always freshly signed.
 *
 * `kind` = a tier ("core" | "pro" | "fleet") or "guide" (free lead magnet).
 * The token is generated by makeClaimProofToken() in claim-proof-download.ts.
 */
export function claimProofDownloadLink(
  baseUrl: string,
  kind: ClaimProofTier | "guide",
  token: string,
): string {
  return `${baseUrl}/api/claimproof/download?item=${kind}&t=${encodeURIComponent(token)}`;
}

/** From address for product emails. Reuses the app's Resend sender env. */
export function getClaimProofFromAddress(): string {
  const addr =
    process.env.BNHG_AUTH_FROM ||
    process.env.AUDIT_FROM_EMAIL ||
    "onboarding@resend.dev";
  return addr.includes("<") ? addr : `Claim Proof <${addr}>`;
}

// --- Buyer log (durable: Neon row, unlike Host's Edge's ephemeral jsonl) ----

/**
 * Record a buyer/lead in newsletter_subscribers with a product-scoped source
 * tag, so the owned list survives Vercel's ephemeral filesystem. Stripe stays
 * the payment record of truth; this is the marketing list. Best-effort: a
 * failure logs and returns false, never throws, so it can't block delivery.
 */
export async function recordClaimProofContact(
  email: string,
  source:
    | "claimproof-guide"
    | "claimproof-core"
    | "claimproof-pro"
    | "claimproof-fleet",
): Promise<boolean> {
  try {
    await sql`
      INSERT INTO newsletter_subscribers (email, source)
      VALUES (${email.toLowerCase().trim()}, ${source})
      ON CONFLICT (email) DO NOTHING
    `;
    return true;
  } catch (err) {
    console.error(`[claim-proof] failed to log contact ${email}:`, err);
    return false;
  }
}

// --- Emails ------------------------------------------------------------------

const EMAIL_SHELL_TOP = `
  <div style="font-family:Helvetica,Arial,sans-serif;color:#2C3E50;max-width:560px;margin:0 auto;padding:24px;">
    <p style="font-size:12px;letter-spacing:0.2em;text-transform:uppercase;color:#B08D57;margin:0 0 16px;">Claim Proof · Be Nice Autos</p>
`;
const EMAIL_SHELL_BOTTOM = `
    <hr style="border:none;border-top:1px solid #F3F4F6;margin:24px 0;" />
    <p style="font-size:12px;line-height:1.55;color:#4B5563;margin:0;">
      Operational guidance, not legal advice. Not affiliated with Turo Inc.
      Trouble with your download? Reply to this email and we&rsquo;ll sort it.
    </p>
  </div>
`;

/** Paid-tier delivery email. Operator voice — direct, warm, zero hype. */
export function claimProofDeliveryEmail(args: {
  name?: string;
  tier: ClaimProofTier;
  /** Token-gated link to /api/claimproof/download (from claimProofDownloadLink). */
  downloadUrl: string;
  /** Fleet only: the walkthrough video URL (CLAIM_PROOF_FLEET_VIDEO_URL). */
  videoUrl?: string;
}): { subject: string; html: string } {
  const first = args.name?.trim().split(/\s+/)[0];
  const hi = first ? `Hi ${first},` : "Hi,";
  const tierLabel = CLAIM_PROOF_TIERS[args.tier].label;
  const subject = `Your Claim Proof ${tierLabel} is here`;

  const videoLine = args.videoUrl
    ? `Your fleet walkthrough video is here: <a href="${args.videoUrl}" style="color:#1A4D4F;font-weight:600;">watch it</a>. `
    : "";
  const fleetExtra =
    args.tier === "fleet"
      ? `<p style="font-size:15px;line-height:1.55;margin:0 0 20px;">
          Your download bundles the Pro manual and the Fleet Operations
          supplement. ${videoLine}You&rsquo;re also on the lifetime-updates
          list — when Turo materially changes its claim or dispute rules, the
          revised edition lands in this inbox at no charge.
        </p>`
      : "";

  const html = `
    ${EMAIL_SHELL_TOP}
    <h1 style="font-size:22px;color:#1a1a1a;margin:0 0 16px;line-height:1.3;">Your ${tierLabel} is ready.</h1>
    <p style="font-size:15px;line-height:1.55;margin:0 0 16px;">${hi}</p>
    <p style="font-size:15px;line-height:1.55;margin:0 0 20px;">
      Thanks for picking up Claim Proof. Here&rsquo;s your download —
      everything is inside, print-ready.
    </p>
    <p style="margin:24px 0;">
      <a href="${args.downloadUrl}" style="background:#B08D57;color:#1a1a1a;padding:14px 24px;text-decoration:none;font-weight:600;border-radius:8px;display:inline-block;">
        Download your kit
      </a>
    </p>
    <p style="font-size:15px;line-height:1.55;margin:0 0 20px;">
      Do one thing today: print the per-trip checklist and put it wherever you
      stage your cars. That single page is the system — the rest of the manual
      is there for the day a guest sends you a photo of something bent.
    </p>
    ${fleetExtra}
    <p style="font-size:14px;line-height:1.55;color:#4B5563;margin:0 0 20px;">
      Guarantee, plainly: run the checklist on your next trip. If it doesn&rsquo;t
      give you cleaner evidence than you&rsquo;ve ever had, reply to this email
      for a full refund — and keep the kit.
    </p>
    ${EMAIL_SHELL_BOTTOM}
  `;

  return { subject, html };
}

/** Free-guide delivery email (lead magnet). Sells softly at the end. */
export function claimProofGuideEmail(args: { downloadUrl: string }): {
  subject: string;
  html: string;
} {
  const subject = "The 24-Hour Rule — your free Turo host guide";
  const html = `
    ${EMAIL_SHELL_TOP}
    <h1 style="font-size:22px;color:#1a1a1a;margin:0 0 16px;line-height:1.3;">The clock starts at trip end.</h1>
    <p style="font-size:15px;line-height:1.55;margin:0 0 20px;">
      Here&rsquo;s your guide. One page of it will save you a claim someday:
      Turo&rsquo;s damage-report window is 24 hours from <strong>trip end</strong> —
      not from when you find the scratch.
    </p>
    <p style="margin:24px 0;">
      <a href="${args.downloadUrl}" style="background:#B08D57;color:#1a1a1a;padding:14px 24px;text-decoration:none;font-weight:600;border-radius:8px;display:inline-block;">
        Get The 24-Hour Rule
      </a>
    </p>
    <p style="font-size:15px;line-height:1.55;margin:0 0 20px;">
      When you&rsquo;re ready for the full system — the 12-shot ritual, ten
      dispute scripts, the appeal workflow, and the desk-arbitration playbook —
      it&rsquo;s all in <a href="https://benicehospitality.com/claimproof" style="color:#1A4D4F;font-weight:600;">Claim Proof</a>,
      built and used daily by a working fleet.
    </p>
    ${EMAIL_SHELL_BOTTOM}
  `;
  return { subject, html };
}
